-- =============================================================================
--  MIGRASI 5 — Kategori makanan + harga paket custom + logo
-- =============================================================================


-- =============================================================================
-- 1. KATEGORI MAKANAN
--    Contoh: "Sando Sandwich", "Croissant", "Kue Ultah"
--    Setiap kategori punya banyak rasa (flavors).
-- =============================================================================

-- Stok sekarang menyatu (satu angka untuk semua rasa), jadi log stok tidak
-- lagi terikat ke satu flavor. Kolomnya dibikin nullable; flavor_id yang
-- terisi berarti log untuk produk itu (produk lama).
alter table public.stock_logs
  drop constraint if exists stock_logs_flavor_id_fkey;
alter table public.stock_logs
  alter column flavor_id drop not null;
alter table public.stock_logs
  add constraint stock_logs_flavor_id_fkey
  foreign key (flavor_id) references public.flavors (id) on delete cascade;

create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  slug        text        not null unique,
  name_id     text        not null,
  name_en     text        not null,
  desc_id     text        not null default '',
  desc_en     text        not null default '',
  image_url   text,
  is_active   boolean     not null default true,
  is_featured boolean     not null default false,
  sort_order  integer     not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists categories_sort_idx on public.categories (sort_order, id);

alter table public.flavors
  add column if not exists category_id bigint references public.categories (id) on delete set null;

create index if not exists flavors_category_idx on public.flavors (category_id);

-- Flavor lama (yang sudah ada sebelum fitur kategori) dibuatkan kategori
-- default supaya tidak ikut hilang dari etalase.
insert into public.categories (slug, name_id, name_en, desc_id, desc_en,
                               is_active, is_featured, sort_order)
values (
  'sando-sandwich',
  'Sando Sandwich',
  'Sando Sandwich',
  'Roti lembut bertenaga dengan isian creamy khas Jepang.',
  'Soft, fluffy bread with our signature creamy fillings.',
  true, true, 1
)
on conflict (slug) do nothing;

-- Pindahkan semua flavor yang belum punya kategori ke kategori default.
update public.flavors
set category_id = (select id from public.categories where slug = 'sando-sandwich')
where category_id is null;

-- RLS kategori
alter table public.categories enable row level security;

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories
for select using (true);

drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories
for all using (public.is_admin()) with check (public.is_admin());

drop trigger if exists categories_touch on public.categories;
create trigger categories_touch before update on public.categories
for each row execute function public.touch_updated_at();


-- =============================================================================
-- 2. HARGA PAKET CUSTOM
--
--    Seller bebas menentukan: beli 2 = 35.000, beli 4 = 65.000, dst.
--    Bentuknya daftar paket di pengaturan:
--      [ { "qty": 2, "price": 35000 }, { "qty": 4, "price": 65000 } ]
--
--    Cara hitung: ambil paket dengan qty TERBESAR yang <= jumlah pesanan.
--    Sisanya dihitung dengan harga satuan biasa.
--
--      1 pcs -> tanpa paket           = 18.000
--      2 pcs -> paket 2              = 35.000
--      3 pcs -> paket 2 + 1 biasa     = 53.000
--      4 pcs -> paket 4              = 65.000
--      5 pcs -> paket 4 + 1 biasa     = 83.000
-- =============================================================================

alter table public.store_settings
  add column if not exists bundle_tiers jsonb not null default '[]'::jsonb;

-- Pindahkan pengaturan lama (paket 2 = 35.000) ke format baru.
update public.store_settings set
  bundle_tiers = '[{"qty": 2, "price": 35000}]'::jsonb
where id = 1
  and (bundle_tiers is null or jsonb_array_length(bundle_tiers) = 0)
  and bundle_enabled;


-- Fungsi bantu: pilih paket-paket yang dipakai untuk sejumlah pcs.
--
-- Paket ditumpuk: pakai paket dengan qty terbesar yang masih muat, sebanyak
-- mungkin, lalu sisanya dibayar harga satuan. Jadi dengan paket
-- (2 = 35.000) dan (4 = 65.000):
--   1 pcs -> 18.000
--   3 pcs -> paket 2 + 1 biasa          = 53.000
--   6 pcs -> paket 4 + paket 2           = 100.000
--   7 pcs -> paket 4 + paket 2 + 1 biasa = 118.000
create or replace function public.pick_bundles(
  p_tiers jsonb,
  p_total integer
) returns jsonb
language plpgsql
immutable
as $$
declare
  v_tier   jsonb;
  v_left   integer := coalesce(p_total, 0);
  v_result jsonb := '[]'::jsonb;
begin
  if p_total is null or p_total < 2
     or jsonb_array_length(coalesce(p_tiers, '[]'::jsonb)) = 0 then
    return v_result;
  end if;

  while v_left >= 2 loop
    -- paket dengan qty terbesar yang masih muat
    v_tier := null;
    select t into v_tier
    from jsonb_array_elements(p_tiers) as t
    where (t ->> 'qty') ~ '^[0-9]+$'
      and (t ->> 'price') ~ '^[0-9]+$'
      and (t ->> 'qty')::int >= 2
      and (t ->> 'qty')::int <= v_left
    order by (t ->> 'qty')::int desc
    limit 1;

    exit when v_tier is null;

    v_result := v_result || jsonb_build_array(v_tier);
    v_left := v_left - (v_tier ->> 'qty')::int;
  end loop;

  return v_result;
end;
$$;


-- =============================================================================
-- 3. create_order dengan paket custom
-- =============================================================================

create or replace function public.create_order(
  p_customer_name    text default '',
  p_phone            text default '',
  p_payment_method   text default 'cash',
  p_delivery_method  text default 'pickup',
  p_address          text default null,
  p_transfer_method  text default null,
  p_payment_proof    text default null,
  p_note             text default null,
  p_language         text default 'id',
  p_items            jsonb default '[]'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings   public.store_settings%rowtype;
  v_item       jsonb;
  v_flavor     public.flavors%rowtype;
  v_order_id   bigint;
  v_flavor_id  bigint;
  v_qty        integer;
  v_name       text;
  v_raw        integer := 0;
  v_count      integer := 0;
  v_bundles    jsonb := '[]'::jsonb;
  v_leftover   integer := 0;
  v_avg_price  integer := 0;
  v_subtotal   integer := 0;
  v_items_ok   integer := 0;
  v_code       text;
  v_proof      text;
  v_delivery   integer := 0;
begin
  if p_customer_name is null or length(trim(p_customer_name)) < 2 then
    raise exception 'invalid_name' using errcode = '22023';
  end if;
  if length(trim(p_customer_name)) > 80 then
    raise exception 'name_too_long' using errcode = '22023';
  end if;
  if p_phone is null or length(public.normalize_phone(p_phone)) < 9 then
    raise exception 'invalid_phone' using errcode = '22023';
  end if;
  if p_payment_method not in ('transfer', 'cash') then
    raise exception 'invalid_payment_method' using errcode = '22023';
  end if;
  if p_delivery_method not in ('pickup', 'delivery') then
    raise exception 'invalid_delivery_method' using errcode = '22023';
  end if;
  if p_delivery_method = 'delivery' and coalesce(length(trim(p_address)), 0) < 5 then
    raise exception 'address_required' using errcode = '22023';
  end if;

  v_proof := nullif(trim(coalesce(p_payment_proof, '')), '');
  if p_payment_method = 'transfer' and v_proof is null then
    raise exception 'proof_required' using errcode = '22023';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_cart' using errcode = '22023';
  end if;
  if jsonb_array_length(p_items) > 30 then
    raise exception 'too_many_items' using errcode = '22023';
  end if;

  select * into v_settings from public.store_settings where id = 1 for update;
  if v_settings.id is null then
    raise exception 'settings_missing' using errcode = '22023';
  end if;
  if not v_settings.is_preorder_open then
    raise exception 'preorder_closed' using errcode = '22023';
  end if;

  -- ---------- validasi rasa & harga mentah ----------
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_flavor_id := (v_item ->> 'flavor_id')::bigint;
    v_qty       := (v_item ->> 'quantity')::integer;

    if v_flavor_id is null or v_qty is null or v_qty < 1 or v_qty > v_settings.max_per_order then
      raise exception 'invalid_quantity' using errcode = '22023';
    end if;

    select * into v_flavor
    from public.flavors
    where id = v_flavor_id and is_active;

    if not found then
      raise exception 'flavor_unavailable' using errcode = '22023';
    end if;

    v_raw      := v_raw + (v_flavor.price * v_qty);
    v_count    := v_count + v_qty;
    v_items_ok := v_items_ok + 1;
  end loop;

  if v_items_ok = 0 then
    raise exception 'empty_cart' using errcode = '22023';
  end if;
  if v_count < v_settings.min_order then
    raise exception 'below_min_order' using errcode = '22023';
  end if;

  -- ---------- pilih paket (bisa ditumpuk) ----------
  v_bundles := case
    when v_settings.bundle_enabled
      then public.pick_bundles(v_settings.bundle_tiers, v_count)
    else '[]'::jsonb
  end;

  v_leftover := v_count - coalesce((
    select sum((b ->> 'qty')::int) from jsonb_array_elements(v_bundles) b
  ), 0);

  -- Kalau paketnya ternyata tidak lebih murah dari beli satuan, lewati.
  if v_bundles <> '[]'::jsonb
     and (select sum((b ->> 'price')::int) from jsonb_array_elements(v_bundles) b)
         >= (v_count - v_leftover) * (v_raw / greatest(v_count, 1)) then
    v_bundles := '[]'::jsonb;
    v_leftover := v_count;
  end if;

  v_avg_price := round(v_raw::numeric / greatest(v_count, 1))::integer;
  v_subtotal  := coalesce((
    select sum((b ->> 'price')::int) from jsonb_array_elements(v_bundles) b
  ), 0) + (v_leftover * v_avg_price);

  v_delivery := case when p_delivery_method = 'delivery' then v_settings.delivery_fee else 0 end;

  -- ---------- stok global ----------
  if v_settings.stock_enabled and v_count > v_settings.total_stock then
    raise exception 'insufficient_stock' using errcode = '22023';
  end if;
  if v_settings.stock_enabled then
    update public.store_settings set total_stock = total_stock - v_count where id = 1;
  end if;

  -- ---------- simpan ----------
  v_code := 'JS-' || to_char(now(), 'YYMMDD') || '-' || lpad(nextval('public.order_code_seq')::text, 3, '0');

  insert into public.orders (
    order_code, customer_name, phone, phone_normalized, delivery_method, address,
    payment_method, transfer_method, payment_proof_path, note,
    subtotal, delivery_fee, total_price, item_count, language
  ) values (
    v_code, trim(p_customer_name), trim(p_phone), public.normalize_phone(p_phone),
    p_delivery_method, nullif(trim(coalesce(p_address, '')), ''),
    p_payment_method, nullif(trim(coalesce(p_transfer_method, '')), ''),
    v_proof, left(coalesce(p_note, ''), 500),
    v_subtotal, v_delivery, v_subtotal + v_delivery, v_count,
    case when p_language = 'en' then 'en' else 'id' end
  )
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_flavor_id := (v_item ->> 'flavor_id')::bigint;
    v_qty       := (v_item ->> 'quantity')::integer;
    select * into v_flavor from public.flavors where id = v_flavor_id;
    v_name := case when coalesce(p_language, 'id') = 'en'
                   then v_flavor.name_en else v_flavor.name_id end;
    insert into public.order_items (
      order_id, flavor_id, flavor_slug, flavor_name, unit_price, quantity, line_total
    ) values (
      v_order_id, v_flavor.id, v_flavor.slug, v_name, v_flavor.price, v_qty, v_flavor.price * v_qty
    );
  end loop;

  return jsonb_build_object(
    'id', v_order_id,
    'order_code', v_code,
    'item_count', v_count,
    'bundles', v_bundles,
    'bundle_count', jsonb_array_length(v_bundles),
    'bundle_qty', v_count - v_leftover,
    'leftover_count', v_leftover,
    'subtotal', v_subtotal,
    'delivery_fee', v_delivery,
    'total_price', v_subtotal + v_delivery,
    'remaining_stock', (select case when stock_enabled then total_stock else null end
                        from public.store_settings where id = 1)
  );
end;
$$;


-- Fungsi bantu untuk frontend: daftar paket aktif
create or replace function public.public_bundle_tiers()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_settings public.store_settings%rowtype;
  v_tiers    jsonb := '[]'::jsonb;
  v_tier     record;
begin
  select * into v_settings from public.store_settings where id = 1;
  if v_settings.id is null or not coalesce(v_settings.bundle_enabled, false) then
    return '[]'::jsonb;
  end if;

  for v_tier in
    select (e ->> 'qty')::int as qty, (e ->> 'price')::int as price
    from jsonb_array_elements(coalesce(v_settings.bundle_tiers, '[]'::jsonb)) as e
    where (e ->> 'qty') ~ '^[0-9]+$' and (e ->> 'price') ~ '^[0-9]+$'
    order by (e ->> 'qty')::int
  loop
    v_tiers := v_tiers || jsonb_build_array(
      jsonb_build_object('qty', v_tier.qty, 'price', v_tier.price)
    );
  end loop;

  return v_tiers;
end;
$$;


-- =============================================================================
-- 4. Kelola kategori
-- =============================================================================

create or replace function public.admin_save_category(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id   bigint := nullif(p_payload ->> 'id', '')::bigint;
  v_slug text;
  v_name text;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  v_name := btrim(coalesce(p_payload ->> 'name_id', ''));
  if v_name = '' then
    raise exception 'invalid_name' using errcode = '22023';
  end if;

  v_slug := lower(regexp_replace(
    trim(both '-' from regexp_replace(coalesce(p_payload ->> 'slug', v_name), '[^a-zA-Z0-9]+', '-', 'g')),
    '-', ''
  ));
  if v_slug = '' then
    v_slug := 'kategori-' || substr(md5(random()::text), 1, 6);
  end if;

  -- Hindari bentrok slug
  if v_id is not null then
    if exists (select 1 from public.categories where slug = v_slug and id <> v_id) then
      v_slug := v_slug || '-' || substr(md5(random()::text), 1, 4);
    end if;
  elsif exists (select 1 from public.categories where slug = v_slug) then
    raise exception 'slug_taken' using errcode = '22023';
  end if;

  if v_id is not null then
    update public.categories set
      slug        = v_slug,
      name_id     = v_name,
      name_en     = coalesce(nullif(btrim(coalesce(p_payload ->> 'name_en', '')), ''), v_name),
      desc_id     = coalesce(p_payload ->> 'desc_id', ''),
      desc_en     = coalesce(p_payload ->> 'desc_en', ''),
      image_url   = case when p_payload ? 'image_url'
                         then nullif(trim(coalesce(p_payload ->> 'image_url', '')), '')
                         else image_url end,
      is_active   = coalesce((p_payload ->> 'is_active')::boolean, true),
      is_featured = coalesce((p_payload ->> 'is_featured')::boolean, false),
      sort_order  = coalesce((p_payload ->> 'sort_order')::integer, 0)
    where id = v_id
    returning id into v_id;
  else
    insert into public.categories (
      slug, name_id, name_en, desc_id, desc_en, image_url,
      is_active, is_featured, sort_order
    ) values (
      v_slug, v_name,
      coalesce(nullif(btrim(coalesce(p_payload ->> 'name_en', '')), ''), v_name),
      coalesce(p_payload ->> 'desc_id', ''),
      coalesce(p_payload ->> 'desc_en', ''),
      nullif(trim(coalesce(p_payload ->> 'image_url', '')), ''),
      coalesce((p_payload ->> 'is_active')::boolean, true),
      coalesce((p_payload ->> 'is_featured')::boolean, false),
      coalesce((p_payload ->> 'sort_order')::integer, 0)
    )
    returning id into v_id;
  end if;

  if v_id is null then
    raise exception 'invalid_payload' using errcode = '22023';
  end if;

  return jsonb_build_object('id', v_id, 'slug', v_slug);
end;
$$;

create or replace function public.admin_delete_category(p_category_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_flavors integer;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  select count(*) into v_flavors
  from public.flavors
  where category_id = p_category_id
    and exists (select 1 from public.orders o
                join public.order_items oi on oi.order_id = o.id
                where oi.flavor_id = flavors.id
                  and o.status in ('pending','accepted','ready'));

  if v_flavors > 0 then
    -- Masih ada rasa yang dipakai pesanan aktif -> nonaktifkan kategorinya
    update public.categories set is_active = false where id = p_category_id;
    return jsonb_build_object('deleted', false, 'deactivated', true);
  end if;

  -- Pindahkan sisa rasa ke kategori pertama yang tersedia
  update public.flavors
  set category_id = (select id from public.categories
                     where id <> p_category_id and is_active
                     order by sort_order, id limit 1)
  where category_id = p_category_id;

  delete from public.categories where id = p_category_id;
  return jsonb_build_object('deleted', true, 'deactivated', false);
end;
$$;

create or replace function public.admin_list_categories()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  return (
    select coalesce(jsonb_agg(
      jsonb_build_object(
        'id', c.id,
        'slug', c.slug,
        'name_id', c.name_id,
        'name_en', c.name_en,
        'desc_id', c.desc_id,
        'desc_en', c.desc_en,
        'image_url', c.image_url,
        'is_active', c.is_active,
        'is_featured', c.is_featured,
        'sort_order', c.sort_order,
        'flavor_count', (select count(*) from public.flavors f
                         where f.category_id = c.id and f.is_active)
      ) order by c.sort_order, c.id
    ), '[]'::jsonb)
    from public.categories c
  );
end;
$$;


-- =============================================================================
-- 5. Flavor ikut menyimpan nama kategori (biar query publik sederhana)
-- =============================================================================

create or replace function public.admin_save_flavor(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id     bigint := nullif(p_payload ->> 'id', '')::bigint;
  v_slug   text;
  v_name   text;
  v_exists boolean;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  v_name := btrim(coalesce(p_payload ->> 'name_id', ''));
  if v_name = '' then
    raise exception 'invalid_name' using errcode = '22023';
  end if;

  v_slug := lower(regexp_replace(trim(both '-' from regexp_replace(
    coalesce(p_payload ->> 'slug', v_name), '[^a-zA-Z0-9]+', '-', 'g')), '-', ''));
  if v_slug = '' then
    v_slug := 'item-' || substr(md5(random()::text), 1, 6);
  end if;

  if v_id is not null then
    if exists (select 1 from public.flavors where slug = v_slug and id <> v_id) then
      v_slug := v_slug || '-' || substr(md5(random()::text), 1, 4);
    end if;
  elsif exists (select 1 from public.flavors where slug = v_slug) then
    raise exception 'slug_taken' using errcode = '22023';
  end if;

  if coalesce((p_payload ->> 'price')::integer, -1) < 0 then
    raise exception 'invalid_price' using errcode = '22023';
  end if;

  if v_id is not null then
    update public.flavors set
      slug          = v_slug,
      name_id       = v_name,
      name_en       = coalesce(nullif(btrim(coalesce(p_payload ->> 'name_en', '')), ''), v_name),
      desc_id       = coalesce(p_payload ->> 'desc_id', ''),
      desc_en       = coalesce(p_payload ->> 'desc_en', ''),
      price         = (p_payload ->> 'price')::integer,
      image_url     = case when p_payload ? 'image_url'
                           then nullif(trim(coalesce(p_payload ->> 'image_url', '')), '')
                           else image_url end,
      is_active     = coalesce((p_payload ->> 'is_active')::boolean, true),
      is_featured   = coalesce((p_payload ->> 'is_featured')::boolean, false),
      sort_order    = coalesce((p_payload ->> 'sort_order')::integer, 0),
      category_id   = case when p_payload ? 'category_id'
                           then nullif(p_payload ->> 'category_id', '')::bigint
                           else category_id end
    where id = v_id
    returning id into v_id;
  else
    insert into public.flavors (
      slug, name_id, name_en, desc_id, desc_en, price, image_url,
      is_active, is_featured, sort_order, category_id
    ) values (
      v_slug, v_name,
      coalesce(nullif(btrim(coalesce(p_payload ->> 'name_en', '')), ''), v_name),
      coalesce(p_payload ->> 'desc_id', ''),
      coalesce(p_payload ->> 'desc_en', ''),
      (p_payload ->> 'price')::integer,
      nullif(trim(coalesce(p_payload ->> 'image_url', '')), ''),
      coalesce((p_payload ->> 'is_active')::boolean, true),
      coalesce((p_payload ->> 'is_featured')::boolean, false),
      coalesce((p_payload ->> 'sort_order')::integer, 0),
      coalesce(nullif(p_payload ->> 'category_id', '')::bigint,
               (select id from public.categories where is_active
                order by sort_order, id limit 1))
    )
    returning id into v_id;
  end if;

  if v_id is null then
    raise exception 'invalid_payload' using errcode = '22023';
  end if;

  return jsonb_build_object('id', v_id, 'slug', v_slug);
end;
$$;


-- =============================================================================
-- 6. admin_save_settings: pakai bundle_tiers
-- =============================================================================

create or replace function public.admin_save_settings(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current public.store_settings%rowtype;
  v_merged  jsonb;
  v_result  jsonb;
  v_tiers   jsonb;
  v_tier    record;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  insert into public.store_settings (id) values (1) on conflict (id) do nothing;
  select * into v_current from public.store_settings where id = 1 for update;

  v_merged := (to_jsonb(v_current) - 'id' - 'updated_at') || (p_payload - 'id' - 'updated_at');

  if not (v_merged ? 'store_name') then
    v_merged := v_merged || jsonb_build_object('store_name', v_current.store_name);
  end if;

  -- Susun daftar paket. Hanya divalidasi bentuknya (qty >= 2, harga >= 0).
  --
  -- PENTING: jangan menyaring berdasarkan harga flavor termurah di toko.
  -- Kalau ada produk murah (mis. croissant Rp15.000) sementara paket untuk
  -- produk lain (Rp18.000), filter seperti itu akan membuang paketnya
  -- dengan sia-sia. Pemeriksaan "paket ini lebih murah atau tidak" dilakukan
  -- per-pesanan di create_order(), memakai harga rata-rata isi keranjang
  -- yang sebenarnya.
  v_tiers := '[]'::jsonb;

  for v_tier in
    select (e ->> 'qty')::int as qty, (e ->> 'price')::int as price
    from jsonb_array_elements(coalesce(v_merged -> 'bundle_tiers', '[]'::jsonb)) as e
    where (e ->> 'qty') ~ '^[0-9]+$' and (e ->> 'price') ~ '^[0-9]+$'
    order by (e ->> 'qty')::int
  loop
    if v_tier.qty >= 2 and v_tier.price >= 0 then
      v_tiers := v_tiers || jsonb_build_array(
        jsonb_build_object('qty', v_tier.qty, 'price', v_tier.price)
      );
    end if;
  end loop;

  update public.store_settings set
    store_name           = coalesce(nullif(btrim(v_merged ->> 'store_name'), ''), v_current.store_name),
    tagline_id           = coalesce(v_merged ->> 'tagline_id', v_current.tagline_id),
    tagline_en           = coalesce(v_merged ->> 'tagline_en', v_current.tagline_en),
    description_id       = coalesce(v_merged ->> 'description_id', v_current.description_id),
    description_en       = coalesce(v_merged ->> 'description_en', v_current.description_en),
    whatsapp             = regexp_replace(coalesce(v_merged ->> 'whatsapp', v_current.whatsapp), '\D', '', 'g'),
    address              = coalesce(v_merged ->> 'address', v_current.address),
    maps_url             = coalesce(v_merged ->> 'maps_url', v_current.maps_url),
    instagram            = coalesce(v_merged ->> 'instagram', v_current.instagram),
    tiktok               = coalesce(v_merged ->> 'tiktok', v_current.tiktok),
    hours_id             = coalesce(v_merged ->> 'hours_id', v_current.hours_id),
    hours_en             = coalesce(v_merged ->> 'hours_en', v_current.hours_en),
    deadline_id          = coalesce(v_merged ->> 'deadline_id', v_current.deadline_id),
    deadline_en          = coalesce(v_merged ->> 'deadline_en', v_current.deadline_en),
    min_order            = case when v_merged ? 'min_order'
                               then greatest(1, coalesce((v_merged ->> 'min_order')::integer, v_current.min_order))
                               else v_current.min_order end,
    max_per_order        = case when v_merged ? 'max_per_order'
                               then greatest(1, coalesce((v_merged ->> 'max_per_order')::integer, v_current.max_per_order))
                               else v_current.max_per_order end,
    delivery_fee         = case when v_merged ? 'delivery_fee'
                               then greatest(0, coalesce((v_merged ->> 'delivery_fee')::integer, v_current.delivery_fee))
                               else v_current.delivery_fee end,
    free_shipping_min    = case when v_merged ? 'free_shipping_min'
                               then greatest(0, coalesce((v_merged ->> 'free_shipping_min')::integer, v_current.free_shipping_min))
                               else v_current.free_shipping_min end,
    bank_accounts        = case when jsonb_typeof(v_merged -> 'bank_accounts') = 'array'
                               then v_merged -> 'bank_accounts' else v_current.bank_accounts end,
    qris_enabled         = coalesce((v_merged ->> 'qris_enabled')::boolean, v_current.qris_enabled),
    qris_image_url       = case when v_merged ? 'qris_image_url'
                               then nullif(trim(coalesce(v_merged ->> 'qris_image_url', '')), '')
                               else v_current.qris_image_url end,
    announcement_id      = coalesce(v_merged ->> 'announcement_id', v_current.announcement_id),
    announcement_en      = coalesce(v_merged ->> 'announcement_en', v_current.announcement_en),
    is_preorder_open     = coalesce((v_merged ->> 'is_preorder_open')::boolean, v_current.is_preorder_open),
    stock_enabled        = coalesce((v_merged ->> 'stock_enabled')::boolean, v_current.stock_enabled),
    total_stock          = case when v_merged ? 'total_stock'
                               then greatest(0, coalesce((v_merged ->> 'total_stock')::integer, v_current.total_stock))
                               else v_current.total_stock end,
    hero_image_url       = case when v_merged ? 'hero_image_url'
                               then nullif(trim(coalesce(v_merged ->> 'hero_image_url', '')), '')
                               else v_current.hero_image_url end,
    hero_image_mobile_url = case when v_merged ? 'hero_image_mobile_url'
                               then nullif(trim(coalesce(v_merged ->> 'hero_image_mobile_url', '')), '')
                               else v_current.hero_image_mobile_url end,
    pickup_note_id       = coalesce(v_merged ->> 'pickup_note_id', v_current.pickup_note_id),
    pickup_note_en       = coalesce(v_merged ->> 'pickup_note_en', v_current.pickup_note_en),
    delivery_note_id     = coalesce(v_merged ->> 'delivery_note_id', v_current.delivery_note_id),
    delivery_note_en     = coalesce(v_merged ->> 'delivery_note_en', v_current.delivery_note_en),
    bundle_enabled       = coalesce((v_merged ->> 'bundle_enabled')::boolean, v_current.bundle_enabled),
    bundle_tiers         = v_tiers,
    logo_url             = case when v_merged ? 'logo_url'
                               then nullif(trim(coalesce(v_merged ->> 'logo_url', '')), '')
                               else v_current.logo_url end,
    brand_line           = coalesce(v_merged ->> 'brand_line', v_current.brand_line)
  where id = 1;

  select to_jsonb(s) into v_result from public.store_settings s where s.id = 1;

  return jsonb_build_object('ok', true,
                            'store_name', v_result ->> 'store_name',
                            'bundle_tiers', v_result -> 'bundle_tiers');
end;
$$;


-- =============================================================================
-- 7. Kolom logo & tagline
-- =============================================================================

alter table public.store_settings
  add column if not exists logo_url   text,
  add column if not exists brand_line text not null default 'Japanese Bake & Pastry';

update public.store_settings set
  brand_line = 'Japanese Bake & Pastry'
where id = 1 and coalesce(brand_line, '') = '';


-- =============================================================================
-- 8. Query publik: kategori beserta rasa di dalamnya
-- =============================================================================

create or replace function public.public_menu()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'id', c.id,
      'slug', c.slug,
      'name_id', c.name_id,
      'name_en', c.name_en,
      'desc_id', c.desc_id,
      'desc_en', c.desc_en,
      'image_url', c.image_url,
      'is_featured', c.is_featured,
      'sort_order', c.sort_order,
      'flavors', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id', f.id,
            'slug', f.slug,
            'name_id', f.name_id,
            'name_en', f.name_en,
            'desc_id', f.desc_id,
            'desc_en', f.desc_en,
            'price', f.price,
            'image_url', f.image_url,
            'is_featured', f.is_featured,
            'sort_order', f.sort_order
          ) order by f.sort_order, f.id
        )
        from public.flavors f
        where f.category_id = c.id and f.is_active
      ), '[]'::jsonb)
    ) order by c.sort_order, c.id
  ), '[]'::jsonb)
  from public.categories c
  where c.is_active;
$$;


-- =============================================================================
-- 9. Segarkan cache PostgREST
-- =============================================================================
notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');
