-- =============================================================================
--  MIGRASI 2 — Stok global, batch pre-order, gambar hero, catatan pengambilan
--  Jalankan: npm run db:push   (aman diulang / idempotent)
-- =============================================================================


-- =============================================================================
-- 1. KOLOM BARU DI store_settings
-- =============================================================================

-- Stok tidak lagi per rasa, melainkan satu stok keseluruhan untuk semua rasa.
alter table public.store_settings
  add column if not exists stock_enabled boolean not null default true,
  add column if not exists total_stock integer not null default 20;

-- Foto background untuk halaman depan (bisa diganti dari dashboard).
-- Idealnya 1920x1080 (16:9) untuk desktop & 1080x1350 (4:5) untuk mobile.
alter table public.store_settings
  add column if not exists hero_image_url       text,
  add column if not exists hero_image_mobile_url text;

-- Catatan cara pengambilan (bisa diganti dari dashboard).
alter table public.store_settings
  add column if not exists pickup_note_id  text not null default '',
  add column if not exists pickup_note_en  text not null default '',
  add column if not exists delivery_note_id text not null default '',
  add column if not exists delivery_note_en text not null default '';

-- Isi nilai awal dari data yang sudah ada.
update public.store_settings
set stock_enabled = coalesce(stock_enabled, true),
    total_stock   = coalesce(total_stock, 20)
where id = 1;

-- Nilai bawaan untuk toko yang belum mengisi catatan.
update public.store_settings set
  pickup_note_id   = coalesce(nullif(pickup_note_id, ''),   'Hanya untuk Vihara Tian En dan UVERS, gratis ongkir. Pengambilan jam 18.00 - 20.00.'),
  pickup_note_en   = coalesce(nullif(pickup_note_en, ''),   'Only at Vihara Tian En and UVERS, free delivery. Pickup hours 18:00 - 20:00.'),
  delivery_note_id = coalesce(nullif(delivery_note_id, ''), 'Ongkir ditanggung sendiri oleh pembeli.'),
  delivery_note_en = coalesce(nullif(delivery_note_en, ''), 'Shipping costs are paid by the customer.')
where id = 1;


-- =============================================================================
-- 2. BATCH PRE-ORDER
--    Pesanan dikelompokkan per "batch" supaya penjual bisa produksi bertahap.
-- =============================================================================

create table if not exists public.batches (
  id          bigint generated by default as identity primary key,
  label       text        not null,                       -- mis. "Batch 1"
  note        text        not null default '',
  status      text        not null default 'open' check (status in ('open','closed')),
  created_at  timestamptz not null default now(),
  closed_at   timestamptz
);

create index if not exists batches_status_idx on public.batches (status, created_at desc);

-- Setiap pesanan punya batch. Batch otomatis dibuat per hari.
alter table public.orders
  add column if not exists batch_id bigint references public.batches (id) on delete set null;

create index if not exists orders_batch_idx on public.orders (batch_id, created_at desc);

-- Backfill: pesanan lama dimasukan ke batch "Arsip".
insert into public.batches (label, note, status, created_at)
select 'Arsip', 'Pesanan sebelum fitur batch diperkenalkan', 'closed', now()
where not exists (select 1 from public.batches);

update public.orders
set batch_id = (select id from public.batches where label = 'Arsip' limit 1)
where batch_id is null;

-- Batch terbuka yang dipakai untuk pesanan baru.
create or replace function public.public_open_batch_id()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  select id into v_id
  from public.batches
  where status = 'open'
  order by created_at desc
  limit 1;

  if v_id is null then
    insert into public.batches (label, note)
    values (
      'Batch ' || to_char(now(), 'DD/MM'),
      'Dibuat otomatis ' || to_char(now(), 'DD MMM YYYY')
    )
    returning id into v_id;
  end if;

  return v_id;
end;
$$;


-- =============================================================================
-- 3. STOK GLOBAL — create_order
--    Stok satu angka untuk semua rasa. Kalau ada order 1 pcs, misal stok
--    20 -> 19 untuk semua rasa.
-- =============================================================================

create or replace function public.create_order(
  p_customer_name    text default '',
  p_phone            text default '',
  p_payment_method   text default 'cash',
  p_delivery_method  text default 'pickup',
  p_address          text default null,
  p_transfer_method  text default null,
  p_payment_proof    text default null,
  p_note             text default null,
  p_language         text default 'id',
  p_items            jsonb default '[]'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings   public.store_settings%rowtype;
  v_item       jsonb;
  v_flavor     public.flavors%rowtype;
  v_order_id   bigint;
  v_flavor_id  bigint;
  v_qty        integer;
  v_name       text;
  v_subtotal   integer := 0;
  v_count      integer := 0;
  v_items_ok   integer := 0;
  v_code       text;
  v_proof      text;
  v_batch_id   bigint;
begin
  -- ---------- validasi input ----------
  if p_customer_name is null or length(trim(p_customer_name)) < 2 then
    raise exception 'invalid_name' using errcode = '22023';
  end if;
  if length(trim(p_customer_name)) > 80 then
    raise exception 'name_too_long' using errcode = '22023';
  end if;

  if p_phone is null or length(public.normalize_phone(p_phone)) < 9 then
    raise exception 'invalid_phone' using errcode = '22023';
  end if;

  if p_payment_method not in ('transfer', 'cash') then
    raise exception 'invalid_payment_method' using errcode = '22023';
  end if;

  if p_delivery_method not in ('pickup', 'delivery') then
    raise exception 'invalid_delivery_method' using errcode = '22023';
  end if;

  if p_delivery_method = 'delivery' and coalesce(length(trim(p_address)), 0) < 5 then
    raise exception 'address_required' using errcode = '22023';
  end if;

  v_proof := nullif(trim(coalesce(p_payment_proof, '')), '');
  if p_payment_method = 'transfer' and v_proof is null then
    raise exception 'proof_required' using errcode = '22023';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_cart' using errcode = '22023';
  end if;
  if jsonb_array_length(p_items) > 30 then
    raise exception 'too_many_items' using errcode = '22023';
  end if;

  -- ---------- ambil settings ----------
  select * into v_settings from public.store_settings where id = 1 for update;
  if v_settings.id is null then
    raise exception 'settings_missing' using errcode = '22023';
  end if;
  if not v_settings.is_preorder_open then
    raise exception 'preorder_closed' using errcode = '22023';
  end if;

  -- ---------- validasi tiap rasa ----------
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_flavor_id := (v_item ->> 'flavor_id')::bigint;
    v_qty       := (v_item ->> 'quantity')::integer;

    if v_flavor_id is null or v_qty is null or v_qty < 1 or v_qty > v_settings.max_per_order then
      raise exception 'invalid_quantity' using errcode = '22023';
    end if;

    select * into v_flavor
    from public.flavors
    where id = v_flavor_id and is_active;

    if not found then
      raise exception 'flavor_unavailable' using errcode = '22023';
    end if;

    v_subtotal := v_subtotal + (v_flavor.price * v_qty);
    v_count    := v_count + v_qty;
    v_items_ok := v_items_ok + 1;
  end loop;

  if v_items_ok = 0 then
    raise exception 'empty_cart' using errcode = '22023';
  end if;

  if v_count < v_settings.min_order then
    raise exception 'below_min_order' using errcode = '22023';
  end if;

  -- ---------- cek & kurangi stok GLOBAL ----------
  -- Stok_settings baris sudah dikunci (for update) di atas, jadi dua pembeli
  -- yang memesan bersamaan tidak akan membuat stok minus.
  if v_settings.stock_enabled and v_count > v_settings.total_stock then
    raise exception 'insufficient_stock' using errcode = '22023';
  end if;

  if v_settings.stock_enabled then
    update public.store_settings
    set total_stock = total_stock - v_count
    where id = 1;
  end if;

  -- ---------- batch ----------
  v_batch_id := public.public_open_batch_id();

  -- ---------- generate kode pesanan ----------
  v_code := 'JS-' || to_char(now(), 'YYMMDD') || '-' || lpad(nextval('public.order_code_seq')::text, 3, '0');

  -- ---------- simpan pesanan ----------
  insert into public.orders (
    order_code, customer_name, phone, phone_normalized, delivery_method, address,
    payment_method, transfer_method, payment_proof_path, note,
    subtotal, delivery_fee, total_price, item_count, language, batch_id
  ) values (
    v_code,
    trim(p_customer_name),
    trim(p_phone),
    public.normalize_phone(p_phone),
    p_delivery_method,
    nullif(trim(coalesce(p_address, '')), ''),
    p_payment_method,
    nullif(trim(coalesce(p_transfer_method, '')), ''),
    v_proof,
    left(coalesce(p_note, ''), 500),
    v_subtotal,
    case when p_delivery_method = 'delivery' then v_settings.delivery_fee else 0 end,
    v_subtotal + case when p_delivery_method = 'delivery' then v_settings.delivery_fee else 0 end,
    v_count,
    case when p_language = 'en' then 'en' else 'id' end,
    v_batch_id
  )
  returning id into v_order_id;

  -- ---------- simpan item ----------
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_flavor_id := (v_item ->> 'flavor_id')::bigint;
    v_qty       := (v_item ->> 'quantity')::integer;

    select * into v_flavor from public.flavors where id = v_flavor_id;

    v_name := case when coalesce(p_language, 'id') = 'en' then v_flavor.name_en else v_flavor.name_id end;

    insert into public.order_items (
      order_id, flavor_id, flavor_slug, flavor_name, unit_price, quantity, line_total
    ) values (
      v_order_id, v_flavor.id, v_flavor.slug, v_name, v_flavor.price, v_qty, v_flavor.price * v_qty
    );
  end loop;

  return jsonb_build_object(
    'id', v_order_id,
    'order_code', v_code,
    'subtotal', v_subtotal,
    'delivery_fee', (select delivery_fee from public.orders where id = v_order_id),
    'total_price', (select total_price from public.orders where id = v_order_id),
    'remaining_stock', (select case when stock_enabled then total_stock else null end
                        from public.store_settings where id = 1)
  );
end;
$$;


-- =============================================================================
-- 4. STOK GLOBAL — admin_update_order_status
--    Tolak => stok global bertambah lagi.
-- =============================================================================

create or replace function public.admin_update_order_status(
  p_order_id   bigint,
  p_new_status text,
  p_admin_note text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if p_new_status not in ('pending','accepted','rejected','ready','delivered','cancelled') then
    raise exception 'invalid_status' using errcode = '22023';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'order_not_found' using errcode = 'P0002';
  end if;
  if v_order.status = p_new_status then
    raise exception 'status_unchanged' using errcode = '22023';
  end if;

  -- MENOLAK => stok global dikembalikan
  if p_new_status in ('rejected', 'cancelled') and v_order.stock_restored = false then
    update public.store_settings
    set total_stock = total_stock + v_order.item_count
    where id = 1 and stock_enabled;

    update public.orders set stock_restored = true where id = p_order_id;
  end if;

  -- Kembalikan pesanan ditolak ke menunggu => stok dipesan lagi
  if v_order.status in ('rejected','cancelled') and p_new_status = 'pending'
     and v_order.stock_restored = true then
    update public.store_settings s
    set total_stock = s.total_stock - v_order.item_count
    where s.id = 1
      and s.stock_enabled
      and s.total_stock >= v_order.item_count;

    if not found then
      raise exception 'insufficient_stock' using errcode = '22023';
    end if;

    update public.orders set stock_restored = false where id = p_order_id;
  end if;

  update public.orders
  set status = p_new_status,
      admin_note = coalesce(nullif(trim(coalesce(p_admin_note, '')), ''), admin_note)
  where id = p_order_id;

  return jsonb_build_object(
    'id', p_order_id,
    'status', p_new_status,
    'total_stock', (select case when stock_enabled then total_stock else null end
                    from public.store_settings where id = 1)
  );
end;
$$;


-- =============================================================================
-- 5. ATUR STOK GLOBAL
-- =============================================================================

create or replace function public.admin_set_stock(
  p_stock integer,
  p_note  text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old integer;
  v_new integer;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;
  if p_stock is null or p_stock < 0 then
    raise exception 'invalid_stock' using errcode = '22023';
  end if;

  select total_stock into v_old from public.store_settings where id = 1 for update;
  if not found then
    raise exception 'settings_missing' using errcode = '22023';
  end if;

  update public.store_settings set total_stock = p_stock where id = 1;
  v_new := p_stock;

  -- flavor_id NULL: log untuk stok gabungan seluruh toko.
  insert into public.stock_logs (flavor_id, delta, reason, note, actor_id)
  values (null, p_stock - v_old, 'global', coalesce(p_note, ''), auth.uid());

  return jsonb_build_object('total_stock', v_new, 'previous', v_old);
end;
$$;


-- =============================================================================
-- 6. DASHBOARD — statistik stok global & per batch
-- =============================================================================

create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'pending_orders',  (select count(*) from public.orders where status = 'pending'),
    'accepted_orders', (select count(*) from public.orders where status = 'accepted'),
    'ready_orders',    (select count(*) from public.orders where status = 'ready'),
    'total_orders',    (select count(*) from public.orders),
    'revenue_today', coalesce((
      select sum(total_price) from public.orders
      where created_at::date = current_date
        and status in ('accepted','ready','delivered')
    ), 0),
    'orders_today',  (select count(*) from public.orders where created_at::date = current_date),
    'revenue_month', coalesce((
      select sum(total_price) from public.orders
      where created_at >= date_trunc('month', now())
        and status in ('accepted','ready','delivered')
    ), 0),
    'flavor_count',  (select count(*) from public.flavors where is_active),
    'stock_enabled', (select stock_enabled from public.store_settings where id = 1),
    'total_stock',   (select total_stock from public.store_settings where id = 1),
    'stock_used', coalesce((
      select sum(item_count) from public.orders
      where status not in ('rejected','cancelled')
        and created_at >= coalesce(
          (select created_at from public.batches where status = 'open' order by created_at desc limit 1),
          '2000-01-01'::timestamptz)
    ), 0),
    'sales_by_flavor', coalesce((
      select jsonb_agg(
        jsonb_build_object('flavor_name', t.flavor_name, 'qty', t.qty)
        order by t.qty desc
      )
      from (
        select oi.flavor_name, sum(oi.quantity)::int as qty
        from public.order_items oi
        join public.orders o on o.id = oi.order_id
        where o.created_at >= date_trunc('month', now())
          and o.status in ('accepted','ready','delivered')
        group by oi.flavor_name
      ) t
    ), '[]'::jsonb)
  );
end;
$$;


-- =============================================================================
-- 7. KELOLA BATCH
-- =============================================================================

create or replace function public.admin_list_batches()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_open_id bigint;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  -- Pastikan ada batch terbuka SEBELUM membaca, supaya batch yang baru
  -- dibuat ikut terlihat di hasil.
  v_open_id := public.public_open_batch_id();

  return (
    select coalesce(jsonb_agg(
      jsonb_build_object(
        'id', b.id,
        'label', b.label,
        'note', b.note,
        'status', b.status,
        'created_at', b.created_at,
        'closed_at', b.closed_at,
        'order_count', (select count(*) from public.orders o where o.batch_id = b.id),
        'item_count', coalesce((select sum(o.item_count) from public.orders o where o.batch_id = b.id), 0),
        'revenue', coalesce((select sum(o.total_price) from public.orders o
                              where o.batch_id = b.id
                                and o.status in ('accepted','ready','delivered')), 0),
        'is_open', (b.id = v_open_id)
      ) order by b.created_at desc
    ), '[]'::jsonb)
    from public.batches b
  );
end;
$$;

create or replace function public.admin_close_batch(p_batch_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  update public.batches
  set status = 'closed', closed_at = now()
  where id = p_batch_id and status = 'open';

  if not found then
    raise exception 'batch_not_open' using errcode = '22023';
  end if;

  return jsonb_build_object('id', p_batch_id, 'status', 'closed');
end;
$$;

create or replace function public.admin_reopen_batch(p_batch_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  -- Tutup batch terbuka lain supaya hanya ada satu.
  update public.batches set status = 'closed', closed_at = coalesce(closed_at, now())
  where status = 'open' and id <> p_batch_id;

  update public.batches
  set status = 'open', closed_at = null
  where id = p_batch_id;

  if not found then
    raise exception 'batch_not_found' using errcode = 'P0002';
  end if;

  return jsonb_build_object('id', p_batch_id, 'status', 'open');
end;
$$;


-- =============================================================================
-- 8. RINGKASAN PER BATCH (untuk dashboard admin)
-- =============================================================================

create or replace function public.admin_batch_summary(p_batch_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'batch', (
      select jsonb_build_object(
        'id', id, 'label', label, 'note', note, 'status', status, 'created_at', created_at
      ) from public.batches where id = p_batch_id
    ),
    'total_orders', (select count(*) from public.orders where batch_id = p_batch_id),
    'total_items',  coalesce((select sum(item_count) from public.orders where batch_id = p_batch_id), 0),
    'revenue',      coalesce((select sum(total_price) from public.orders
                              where batch_id = p_batch_id
                                and status in ('accepted','ready','delivered')), 0),
    'by_flavor', coalesce((
      select jsonb_agg(
        jsonb_build_object('flavor_name', t.flavor_name, 'qty', t.qty)
        order by t.qty desc
      )
      from (
        select oi.flavor_name, sum(oi.quantity)::int as qty
        from public.order_items oi
        join public.orders o on o.id = oi.order_id
        where o.batch_id = p_batch_id
        group by oi.flavor_name
      ) t
    ), '[]'::jsonb),
    'by_delivery', coalesce((
      select jsonb_object_agg(delivery_method, cnt)
      from (
        select delivery_method, count(*)::int as cnt
        from public.orders where batch_id = p_batch_id
        group by delivery_method
      ) c
    ), '{}'::jsonb)
  );
end;
$$;


-- =============================================================================
-- 9. RLS untuk tabel batches
-- =============================================================================

alter table public.batches enable row level security;

drop policy if exists batches_admin_all on public.batches;
create policy batches_admin_all on public.batches
for all using (public.is_admin()) with check (public.is_admin());

-- =============================================================================
-- 11. SIMPAN PENGATURAN (termasuk kolom baru)
-- =============================================================================

create or replace function public.admin_save_settings(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  insert into public.store_settings (
    id, store_name, tagline_id, tagline_en, description_id, description_en,
    whatsapp, address, maps_url, instagram, tiktok, hours_id, hours_en,
    deadline_id, deadline_en, min_order, max_per_order, delivery_fee,
    free_shipping_min, bank_accounts, qris_enabled, qris_image_url,
    announcement_id, announcement_en, is_preorder_open,
    stock_enabled, total_stock, hero_image_url, hero_image_mobile_url,
    pickup_note_id, pickup_note_en, delivery_note_id, delivery_note_en
  ) values (
    1,
    coalesce(nullif(btrim(p_payload ->> 'store_name'), ''), 'Japanese Sando'),
    coalesce(p_payload ->> 'tagline_id', ''),
    coalesce(p_payload ->> 'tagline_en', ''),
    coalesce(p_payload ->> 'description_id', ''),
    coalesce(p_payload ->> 'description_en', ''),
    regexp_replace(coalesce(p_payload ->> 'whatsapp', ''), '\D', '', 'g'),
    coalesce(p_payload ->> 'address', ''),
    coalesce(p_payload ->> 'maps_url', ''),
    coalesce(p_payload ->> 'instagram', ''),
    coalesce(p_payload ->> 'tiktok', ''),
    coalesce(p_payload ->> 'hours_id', ''),
    coalesce(p_payload ->> 'hours_en', ''),
    coalesce(p_payload ->> 'deadline_id', ''),
    coalesce(p_payload ->> 'deadline_en', ''),
    greatest(1, coalesce((p_payload ->> 'min_order')::integer, 1)),
    greatest(1, coalesce((p_payload ->> 'max_per_order')::integer, 20)),
    greatest(0, coalesce((p_payload ->> 'delivery_fee')::integer, 0)),
    greatest(0, coalesce((p_payload ->> 'free_shipping_min')::integer, 0)),
    case when jsonb_typeof(p_payload -> 'bank_accounts') = 'array'
         then p_payload -> 'bank_accounts' else '[]'::jsonb end,
    coalesce((p_payload ->> 'qris_enabled')::boolean, false),
    nullif(trim(coalesce(p_payload ->> 'qris_image_url', '')), ''),
    coalesce(p_payload ->> 'announcement_id', ''),
    coalesce(p_payload ->> 'announcement_en', ''),
    coalesce((p_payload ->> 'is_preorder_open')::boolean, true),
    coalesce((p_payload ->> 'stock_enabled')::boolean, true),
    greatest(0, coalesce((p_payload ->> 'total_stock')::integer, 20)),
    nullif(trim(coalesce(p_payload ->> 'hero_image_url', '')), ''),
    nullif(trim(coalesce(p_payload ->> 'hero_image_mobile_url', '')), ''),
    coalesce(p_payload ->> 'pickup_note_id', ''),
    coalesce(p_payload ->> 'pickup_note_en', ''),
    coalesce(p_payload ->> 'delivery_note_id', ''),
    coalesce(p_payload ->> 'delivery_note_en', '')
  )
  on conflict (id) do update set
    store_name        = excluded.store_name,
    tagline_id        = excluded.tagline_id,
    tagline_en        = excluded.tagline_en,
    description_id    = excluded.description_id,
    description_en    = excluded.description_en,
    whatsapp          = excluded.whatsapp,
    address           = excluded.address,
    maps_url          = excluded.maps_url,
    instagram         = excluded.instagram,
    tiktok            = excluded.tiktok,
    hours_id          = excluded.hours_id,
    hours_en          = excluded.hours_en,
    deadline_id       = excluded.deadline_id,
    deadline_en       = excluded.deadline_en,
    min_order         = excluded.min_order,
    max_per_order     = excluded.max_per_order,
    delivery_fee      = excluded.delivery_fee,
    free_shipping_min = excluded.free_shipping_min,
    bank_accounts     = excluded.bank_accounts,
    qris_enabled      = excluded.qris_enabled,
    qris_image_url    = excluded.qris_image_url,
    announcement_id   = excluded.announcement_id,
    announcement_en   = excluded.announcement_en,
    is_preorder_open  = excluded.is_preorder_open,
    stock_enabled     = excluded.stock_enabled,
    total_stock       = excluded.total_stock,
    hero_image_url    = excluded.hero_image_url,
    hero_image_mobile_url = excluded.hero_image_mobile_url,
    pickup_note_id    = excluded.pickup_note_id,
    pickup_note_en    = excluded.pickup_note_en,
    delivery_note_id  = excluded.delivery_note_id,
    delivery_note_en  = excluded.delivery_note_en;

  return jsonb_build_object('ok', true);
end;
$$;


-- =============================================================================
-- 12. Daftar pesanan — ikutkan kolom batch
-- =============================================================================

create or replace function public.admin_list_orders(
  p_status  text default null,
  p_search  text default null,
  p_limit   integer default 50,
  p_offset  integer default 0
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  return (
    with filtered as (
      select o.*
      from public.orders o
      where (p_status is null or o.status = p_status)
        and (
          p_search is null
          or btrim(p_search) = ''
          or o.order_code ilike '%' || p_search || '%'
          or o.customer_name ilike '%' || p_search || '%'
          or o.phone ilike '%' || p_search || '%'
        )
      order by o.created_at desc
      limit greatest(1, least(p_limit, 200))
      offset greatest(0, p_offset)
    )
    select jsonb_build_object(
      'orders', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id', f.id,
            'order_code', f.order_code,
            'customer_name', f.customer_name,
            'phone', f.phone,
            'delivery_method', f.delivery_method,
            'address', f.address,
            'payment_method', f.payment_method,
            'transfer_method', f.transfer_method,
            'payment_proof_path', f.payment_proof_path,
            'note', f.note,
            'admin_note', f.admin_note,
            'subtotal', f.subtotal,
            'delivery_fee', f.delivery_fee,
            'total_price', f.total_price,
            'item_count', f.item_count,
            'status', f.status,
            'language', f.language,
            'batch_id', f.batch_id,
            'batch_label', (select label from public.batches where id = f.batch_id),
            'created_at', f.created_at,
            'updated_at', f.updated_at,
            'items', coalesce((
              select jsonb_agg(jsonb_build_object(
                'flavor_name', oi.flavor_name,
                'quantity', oi.quantity,
                'unit_price', oi.unit_price,
                'line_total', oi.line_total
              ) order by oi.id)
              from public.order_items oi where oi.order_id = f.id
            ), '[]'::jsonb)
          ) order by f.created_at desc
        ) from filtered f
      ), '[]'::jsonb),
      'total', (select count(*) from filtered)
    )
  );
end;
$$;


-- =============================================================================
-- 13. Segarkan cache PostgREST
-- =============================================================================
notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');

