-- =============================================================================
--  Japanese Sando â€” Pre-Order Database Schema
--  Jalankan file ini sekali di Supabase Dashboard > SQL Editor > New query
--  (atau lewat: npm run db:push)
-- =============================================================================

create extension if not exists "pgcrypto";

-- =============================================================================
-- 1. TABEL
-- =============================================================================

-- Produk / rasa sando -------------------------------------------------------
create table if not exists public.flavors (
  id              bigint generated by default as identity primary key,
  slug            text        not null unique,
  name_id         text        not null,
  name_en         text        not null,
  desc_id         text        not null default '',
  desc_en         text        not null default '',
  price           integer     not null check (price >= 0),
  image_url       text,
  is_active       boolean     not null default true,   -- tampil / tidak di etalase
  is_featured     boolean     not null default false,  --/Unggulan di landing page
  stock_enabled   boolean     not null default true,   -- false = stok tak terbatas
  stock           integer     not null default 0 check (stock >= 0),
  sort_order      integer     not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Pengaturan toko (baris tunggal, id = 1) ----------------------------------
create table if not exists public.store_settings (
  id                  smallint    primary key default 1 check (id = 1),
  store_name          text        not null default 'Japanese Sando',
  tagline_id          text        not null default 'Roti Sederhana, Rasa Luar Biasa',
  tagline_en          text        not null default 'Simple Bread, Extraordinary Flavors',
  description_id      text        not null default '',
  description_en      text        not null default '',
  whatsapp            text        not null default '',  -- format internasional, mis. 6281234567890
  address             text        not null default '',
  maps_url            text        not null default '',
  instagram           text        not null default '',
  tiktok              text        not null default '',
  hours_id            text        not null default '',
  hours_en            text        not null default '',
  deadline_id         text        not null default 'Pesanan ditutup pukul 21.00 WIB',
  deadline_en         text        not null default 'Orders close at 9:00 PM (GMT+7)',
  min_order           integer     not null default 1 check (min_order >= 1),
  max_per_order       integer     not null default 20 check (max_per_order >= 1),
  delivery_fee        integer     not null default 0 check (delivery_fee >= 0),
  free_shipping_min   integer     not null default 0 check (free_shipping_min >= 0),
  bank_accounts       jsonb       not null default '[]'::jsonb,
  qris_enabled        boolean     not null default false,
  qris_image_url      text,
  announcement_id     text        not null default '',
  announcement_en     text        not null default '',
  is_preorder_open    boolean     not null default true,
  updated_at          timestamptz not null default now()
);

-- Pesanan -------------------------------------------------------------------
create table if not exists public.orders (
  id                  bigint generated by default as identity primary key,
  order_code          text        not null unique,
  customer_name       text        not null,
  phone               text        not null,
  phone_normalized    text        not null,
  delivery_method     text        not null default 'pickup'
                      check (delivery_method in ('pickup','delivery')),
  address             text,
  payment_method      text        not null check (payment_method in ('transfer','cash')),
  transfer_method     text,       -- bank / ewallet / qris (opsional)
  payment_proof_path  text,
  note                text        not null default '',
  admin_note          text        not null default '',
  subtotal            integer     not null default 0,
  delivery_fee        integer     not null default 0,
  total_price         integer     not null default 0,
  item_count          integer     not null default 0,
  status              text        not null default 'pending'
                      check (status in ('pending','accepted','rejected','ready','delivered','cancelled')),
  stock_restored      boolean     not null default false,
  language            text        not null default 'id',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists orders_status_idx     on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_phone_idx      on public.orders (phone_normalized);
create index if not exists orders_code_idx       on public.orders (order_code);

-- Item pesanan (snapshot harga & nama saat order dibuat) --------------------
create table if not exists public.order_items (
  id            bigint generated by default as identity primary key,
  order_id      bigint    not null references public.orders (id) on delete cascade,
  flavor_id     bigint    references public.flavors (id) on delete set null,
  flavor_slug   text      not null,
  flavor_name   text      not null,
  unit_price    integer   not null,
  quantity      integer   not null check (quantity > 0),
  line_total    integer   not null,
  created_at    timestamptz not null default now()
);

create index if not exists order_items_order_idx on public.order_items (order_id);

-- Admin / user aplikasi -----------------------------------------------------
create table if not exists public.admins (
  user_id     uuid        primary key references auth.users (id) on delete cascade,
  email       text        not null,
  full_name   text        not null default '',
  role        text        not null default 'owner' check (role in ('owner','staff')),
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now()
);

-- Riwayat perubahan stok (audit trail, opsional tapi berguna) ---------------
create table if not exists public.stock_logs (
  id          bigint generated by default as identity primary key,
  flavor_id   bigint    not null references public.flavors (id) on delete cascade,
  delta       integer   not null,
  reason      text      not null default 'manual',
  note        text      not null default '',
  actor_id    uuid,
  created_at  timestamptz not null default now()
);

create index if not exists stock_logs_flavor_idx on public.stock_logs (flavor_id, created_at desc);

-- =============================================================================
-- 2. TRIGGER
-- =============================================================================

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists flavors_touch on public.flavors;
create trigger flavors_touch before update on public.flavors
for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch before update on public.orders
for each row execute function public.touch_updated_at();

drop trigger if exists settings_touch on public.store_settings;
create trigger settings_touch before update on public.store_settings
for each row execute function public.touch_updated_at();

-- Bootstrap admin: user pertama yang mendaftar otomatis menjadi admin.
create or replace function public.handle_first_user_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.admins) then
    insert into public.admins (user_id, email, full_name)
    values (
      new.id,
      new.email,
      coalesce(new.raw_user_meta_data ->> 'full_name', '')
    );
  end if;
  return new;
end;
$$;

drop trigger if exists on_first_user_created on auth.users;
create trigger on_first_user_created
after insert on auth.users
for each row execute function public.handle_first_user_admin();

-- =============================================================================
-- 3. FUNGSI BANTU
-- =============================================================================

-- Cephak ke user yang sedang login (null untuk anon)
create or replace function public.current_admin_id()
returns uuid
language sql
stable
set search_path = public
as $$
  select auth.uid();
$$;

-- True bila user yang sedang login adalah admin aktif
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins
    where user_id = auth.uid() and is_active
  );
$$;

create or replace function public.normalize_phone(p_phone text)
returns text
language plpgsql
immutable
as $$
declare
  v text;
begin
  v := regexp_replace(coalesce(p_phone, ''), '\D', '', 'g');
  if length(v) = 0 then
    return v;
  end if;
  if v like '62%' then
    return v;                              -- sudah format internasional
  end if;
  if v like '0%' then
    return '62' || substring(v from 2);     -- 0812... -> 62812...
  end if;
  return v;
end;
$$;

-- Nomor urut untuk kode pesanan (JS-YYMMDD-001) ------------------------------
create sequence if not exists public.order_code_seq start 1;

-- =============================================================================
-- 4. FUNGSI PUBLIK â€” BUAT PESANAN (dipanggil pembeli, tanpa login)
--    Harga SELALU diambil dari server, tidak pernah dipercaya dari klien.
-- =============================================================================
create or replace function public.create_order(
  p_customer_name    text default '',
  p_phone            text default '',
  p_payment_method   text default 'cash',
  p_delivery_method  text default 'pickup',
  p_address          text default null,
  p_transfer_method  text default null,
  p_payment_proof    text default null,
  p_note             text default null,
  p_language         text default 'id',
  p_items            jsonb default '[]'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings   public.store_settings%rowtype;
  v_item       jsonb;
  v_flavor     public.flavors%rowtype;
  v_order_id   bigint;
  v_flavor_id  bigint;
  v_qty        integer;
  v_name       text;
  v_subtotal   integer := 0;
  v_count      integer := 0;
  v_items_ok   integer := 0;
  v_code       text;
  v_proof      text;
begin
  -- ---------- validasi input ----------
  if p_customer_name is null or length(trim(p_customer_name)) < 2 then
    raise exception 'invalid_name' using errcode = '22023';
  end if;
  if length(trim(p_customer_name)) > 80 then
    raise exception 'name_too_long' using errcode = '22023';
  end if;

  if p_phone is null or length(public.normalize_phone(p_phone)) < 9 then
    raise exception 'invalid_phone' using errcode = '22023';
  end if;

  if p_payment_method not in ('transfer', 'cash') then
    raise exception 'invalid_payment_method' using errcode = '22023';
  end if;

  if p_delivery_method not in ('pickup', 'delivery') then
    raise exception 'invalid_delivery_method' using errcode = '22023';
  end if;

  if p_delivery_method = 'delivery' and coalesce(length(trim(p_address)), 0) < 5 then
    raise exception 'address_required' using errcode = '22023';
  end if;

  v_proof := nullif(trim(coalesce(p_payment_proof, '')), '');
  if p_payment_method = 'transfer' and v_proof is null then
    raise exception 'proof_required' using errcode = '22023';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_cart' using errcode = '22023';
  end if;
  if jsonb_array_length(p_items) > 30 then
    raise exception 'too_many_items' using errcode = '22023';
  end if;

  -- ---------- ambil settings ----------
  select * into v_settings from public.store_settings where id = 1;
  if v_settings.id is null then
    raise exception 'settings_missing' using errcode = '22023';
  end if;
  if not v_settings.is_preorder_open then
    raise exception 'preorder_closed' using errcode = '22023';
  end if;

  -- ---------- validasi + kunci tiap rasa ----------
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_flavor_id := (v_item ->> 'flavor_id')::bigint;
    v_qty       := (v_item ->> 'quantity')::integer;

    if v_flavor_id is null or v_qty is null or v_qty < 1 or v_qty > v_settings.max_per_order then
      raise exception 'invalid_quantity' using errcode = '22023';
    end if;

    select * into v_flavor
    from public.flavors
    where id = v_flavor_id and is_active
    for update;                                   -- kunci baris, mencegah stok bentrok

    if not found then
      raise exception 'flavor_unavailable' using errcode = '22023';
    end if;

    if v_flavor.stock_enabled and v_flavor.stock < v_qty then
      raise exception 'insufficient_stock' using errcode = '22023';
    end if;

    v_subtotal := v_subtotal + (v_flavor.price * v_qty);
    v_count    := v_count + v_qty;
    v_items_ok := v_items_ok + 1;
  end loop;

  if v_items_ok = 0 then
    raise exception 'empty_cart' using errcode = '22023';
  end if;

  if v_count < v_settings.min_order then
    raise exception 'below_min_order' using errcode = '22023';
  end if;

  -- ---------- generate kode pesanan (sequence, selalu unik) ----------
  v_code := 'JS-' || to_char(now(), 'YYMMDD') || '-' || lpad(nextval('public.order_code_seq')::text, 3, '0');

  -- ---------- simpan pesanan ----------
  insert into public.orders (
    order_code, customer_name, phone, phone_normalized, delivery_method, address,
    payment_method, transfer_method, payment_proof_path, note,
    subtotal, delivery_fee, total_price, item_count, language
  ) values (
    v_code,
    trim(p_customer_name),
    trim(p_phone),
    public.normalize_phone(p_phone),
    p_delivery_method,
    nullif(trim(coalesce(p_address, '')), ''),
    p_payment_method,
    nullif(trim(coalesce(p_transfer_method, '')), ''),
    v_proof,
    left(coalesce(p_note, ''), 500),
    v_subtotal,
    case when p_delivery_method = 'delivery' then v_settings.delivery_fee else 0 end,
    v_subtotal + case when p_delivery_method = 'delivery' then v_settings.delivery_fee else 0 end,
    v_count,
    case when p_language = 'en' then 'en' else 'id' end
  )
  returning id into v_order_id;

  -- ---------- simpan item ----------
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_flavor_id := (v_item ->> 'flavor_id')::bigint;
    v_qty       := (v_item ->> 'quantity')::integer;

    select * into v_flavor from public.flavors where id = v_flavor_id;

    v_name := case when coalesce(p_language, 'id') = 'en' then v_flavor.name_en else v_flavor.name_id end;

    insert into public.order_items (
      order_id, flavor_id, flavor_slug, flavor_name, unit_price, quantity, line_total
    ) values (
      v_order_id, v_flavor.id, v_flavor.slug, v_name, v_flavor.price, v_qty, v_flavor.price * v_qty
    );
  end loop;

  -- ---------- kurangi stok ----------
  -- Stok langsung berkurang begitu pembeli mengirim pre-order, tanpa menunggu
  -- keputusan admin. Ini mencegah produk terjual habis padahal pesanan sudah
  -- masuk.
  --
  -- Kalau nanti admin MENOLAK pesanan ini, stok dikembalikan lagi oleh
  -- admin_update_order_status() (lihat blok "tolak => stok dikembalikan").
  --
  -- Produk dengan stock_enabled = false (stok tak terbatas) tidak terpengaruh.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_flavor_id := (v_item ->> 'flavor_id')::bigint;
    v_qty       := (v_item ->> 'quantity')::integer;

    update public.flavors
    set stock = stock - v_qty
    where id = v_flavor_id and stock_enabled;
  end loop;

  -- ---------- generate kode pesanan sudah dilakukan di atas ----------

  return jsonb_build_object(
    'id', v_order_id,
    'order_code', v_code,
    'subtotal', v_subtotal,
    'delivery_fee', (select delivery_fee from public.orders where id = v_order_id),
    'total_price', (select total_price from public.orders where id = v_order_id)
  );
end;
$$;

-- Lacak pesanan dengan kode + nomor telepon ---------------------------------
create or replace function public.track_order(p_code text, p_phone text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_items jsonb;
begin
  select * into v_order
  from public.orders
  where upper(order_code) = upper(trim(coalesce(p_code, '')))
    and phone_normalized = public.normalize_phone(p_phone)
  limit 1;

  if not found then
    return null;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'flavor_name', flavor_name,
    'quantity', quantity,
    'unit_price', unit_price,
    'line_total', line_total
  ) order by id), '[]'::jsonb)
  into v_items
  from public.order_items where order_id = v_order.id;

  return jsonb_build_object(
    'order_code', v_order.order_code,
    'customer_name', v_order.customer_name,
    'phone', v_order.phone,
    'status', v_order.status,
    'delivery_method', v_order.delivery_method,
    'address', v_order.address,
    'payment_method', v_order.payment_method,
    'note', v_order.note,
    'subtotal', v_order.subtotal,
    'delivery_fee', v_order.delivery_fee,
    'total_price', v_order.total_price,
    'item_count', v_order.item_count,
    'language', v_order.language,
    'created_at', v_order.created_at,
    'updated_at', v_order.updated_at,
    'items', v_items
  );
end;
$$;

-- =============================================================================
-- 5. FUNGSI ADMIN (self-authorized lewat is_admin())
-- =============================================================================

-- Daftar pesanan untuk dashboard ---------------------------------------------
create or replace function public.admin_list_orders(
  p_status  text default null,
  p_search  text default null,
  p_limit   integer default 50,
  p_offset  integer default 0
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  return (
    with filtered as (
      select o.*
      from public.orders o
      where (p_status is null or o.status = p_status)
        and (
          p_search is null
          or btrim(p_search) = ''
          or o.order_code ilike '%' || p_search || '%'
          or o.customer_name ilike '%' || p_search || '%'
          or o.phone ilike '%' || p_search || '%'
        )
      order by o.created_at desc
      limit greatest(1, least(p_limit, 200))
      offset greatest(0, p_offset)
    )
    select jsonb_build_object(
      'orders', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id', f.id,
            'order_code', f.order_code,
            'customer_name', f.customer_name,
            'phone', f.phone,
            'delivery_method', f.delivery_method,
            'address', f.address,
            'payment_method', f.payment_method,
            'transfer_method', f.transfer_method,
            'payment_proof_path', f.payment_proof_path,
            'note', f.note,
            'admin_note', f.admin_note,
            'subtotal', f.subtotal,
            'delivery_fee', f.delivery_fee,
            'total_price', f.total_price,
            'item_count', f.item_count,
            'status', f.status,
            'language', f.language,
            'created_at', f.created_at,
            'updated_at', f.updated_at,
            'items', coalesce((
              select jsonb_agg(jsonb_build_object(
                'flavor_name', oi.flavor_name,
                'quantity', oi.quantity,
                'unit_price', oi.unit_price,
                'line_total', oi.line_total
              ) order by oi.id)
              from public.order_items oi where oi.order_id = f.id
            ), '[]'::jsonb)
          ) order by f.created_at desc
        ) from filtered f
      ), '[]'::jsonb),
      'total', (select count(*) from filtered)
    )
  );
end;
$$;

-- Ubah status pesanan (+/âˆ’ stok otomatis) -----------------------------------
create or replace function public.admin_update_order_status(
  p_order_id   bigint,
  p_new_status text,
  p_admin_note text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if p_new_status not in ('pending','accepted','rejected','ready','delivered','cancelled') then
    raise exception 'invalid_status' using errcode = '22023';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'order_not_found' using errcode = 'P0002';
  end if;
  if v_order.status = p_new_status then
    raise exception 'status_unchanged' using errcode = '22023';
  end if;

  -- MENOLAK => stok dikembalikan ke rak.
  -- (Status "cancelled" tidak lagi dipakai penjual, tapi pesanan lama
  --  berstatus itu tetap bisa dikembalikan agar tidak menggantung.)
  if p_new_status in ('rejected', 'cancelled') and v_order.stock_restored = false then
    update public.flavors f
    set stock = f.stock + it.qty
    from (
      select oi.flavor_id, sum(oi.quantity)::int as qty
      from public.order_items oi
      where oi.order_id = p_order_id and oi.flavor_id is not null
      group by oi.flavor_id
    ) it
    where f.id = it.flavor_id and f.stock_enabled;

    update public.orders set stock_restored = true where id = p_order_id;
  end if;

  -- Kembalikan pesanan yang ditolak ke status menunggu => stok dipesan lagi
  -- (gagal kalau stok meantime sudah habis dipakai pesanan lain).
  if v_order.status in ('rejected', 'cancelled') and p_new_status = 'pending' and v_order.stock_restored = true then
    update public.flavors f
    set stock = f.stock - it.qty
    from (
      select oi.flavor_id, sum(oi.quantity)::int as qty
      from public.order_items oi
      where oi.order_id = p_order_id and oi.flavor_id is not null
      group by oi.flavor_id
    ) it
    where f.id = it.flavor_id and f.stock_enabled
      and f.stock >= it.qty;

    if not found then
      raise exception 'insufficient_stock' using errcode = '22023';
    end if;

    update public.orders set stock_restored = false where id = p_order_id;
  end if;

  update public.orders
  set status = p_new_status,
      admin_note = coalesce(nullif(trim(coalesce(p_admin_note, '')), ''), admin_note)
  where id = p_order_id;

  return jsonb_build_object('id', p_order_id, 'status', p_new_status);
end;
$$;

-- Tambah admin lain --------------------------------------------------------
create or replace function public.admin_list_users()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;
  return (
    select coalesce(jsonb_agg(jsonb_build_object(
      'user_id', a.user_id, 'email', a.email, 'full_name', a.full_name,
      'role', a.role, 'is_active', a.is_active, 'created_at', a.created_at
    ) order by a.created_at), '[]'::jsonb)
    from public.admins a
  );
end;
$$;

-- Simpan produk (id ada = update, id kosong = insert baru) -------------------
create or replace function public.admin_save_flavor(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id     bigint := nullif(p_payload ->> 'id', '')::bigint;
  v_slug   text;
  v_name   text;
  v_exists boolean;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  v_name := btrim(coalesce(p_payload ->> 'name_id', ''));
  if v_name = '' then
    raise exception 'invalid_name' using errcode = '22023';
  end if;

  v_slug := lower(regexp_replace(trim(coalesce(p_payload ->> 'slug', v_name)), '[^a-zA-Z0-9]+', '-', 'g'));
  v_slug := trim(both '-' from v_slug);
  if v_slug = '' then
    v_slug := 'item-' || substr(md5(random()::text), 1, 8);
  end if;

  -- Hindari bentrok slug dengan produk lain
  if v_id is not null then
    select exists (select 1 from public.flavors where slug = v_slug and id <> v_id) into v_exists;
  else
    select exists (select 1 from public.flavors where slug = v_slug) into v_exists;
  end if;
  if v_exists then
    v_slug := v_slug || '-' || substr(md5(random()::text), 1, 4);
  end if;

  if coalesce((p_payload ->> 'price')::integer, -1) < 0 then
    raise exception 'invalid_price' using errcode = '22023';
  end if;

  if v_id is not null then
    update public.flavors set
      slug          = v_slug,
      name_id       = v_name,
      name_en       = coalesce(nullif(btrim(p_payload ->> 'name_en'), ''), v_name),
      desc_id       = coalesce(p_payload ->> 'desc_id', ''),
      desc_en       = coalesce(p_payload ->> 'desc_en', ''),
      price         = (p_payload ->> 'price')::integer,
      image_url     = nullif(trim(coalesce(p_payload ->> 'image_url', '')), ''),
      is_active     = coalesce((p_payload ->> 'is_active')::boolean, true),
      is_featured   = coalesce((p_payload ->> 'is_featured')::boolean, false),
      stock_enabled = coalesce((p_payload ->> 'stock_enabled')::boolean, true),
      stock         = greatest(0, coalesce((p_payload ->> 'stock')::integer, 0)),
      sort_order    = coalesce((p_payload ->> 'sort_order')::integer, 0)
    where id = v_id
    returning id into v_id;
  else
    insert into public.flavors (
      slug, name_id, name_en, desc_id, desc_en, price, image_url,
      is_active, is_featured, stock_enabled, stock, sort_order
    ) values (
      v_slug,
      v_name,
      coalesce(nullif(btrim(p_payload ->> 'name_en'), ''), v_name),
      coalesce(p_payload ->> 'desc_id', ''),
      coalesce(p_payload ->> 'desc_en', ''),
      (p_payload ->> 'price')::integer,
      nullif(trim(coalesce(p_payload ->> 'image_url', '')), ''),
      coalesce((p_payload ->> 'is_active')::boolean, true),
      coalesce((p_payload ->> 'is_featured')::boolean, false),
      coalesce((p_payload ->> 'stock_enabled')::boolean, true),
      greatest(0, coalesce((p_payload ->> 'stock')::integer, 0)),
      coalesce((p_payload ->> 'sort_order')::integer, 0)
    )
    returning id into v_id;
  end if;

  if v_id is null then
    raise exception 'invalid_payload' using errcode = '22023';
  end if;

  return jsonb_build_object('id', v_id, 'slug', v_slug);
end;
$$;

-- Hapus produk --------------------------------------------------------------
create or replace function public.admin_delete_flavor(p_flavor_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if exists (
    select 1 from public.order_items
    where flavor_id = p_flavor_id
      and order_id in (select id from public.orders where status in ('pending','accepted','ready'))
  ) then
    -- ada pesanan aktif -> nonaktifkan saja, jangan dihapus
    update public.flavors set is_active = false where id = p_flavor_id;
    return jsonb_build_object('deleted', false, 'deactivated', true);
  end if;

  delete from public.flavors where id = p_flavor_id;
  return jsonb_build_object('deleted', true, 'deactivated', false);
end;
$$;

-- Atur stok -----------------------------------------------------------------
create or replace function public.admin_set_stock(
  p_flavor_id bigint,
  p_stock     integer,
  p_note      text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old integer;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;
  if p_stock is null or p_stock < 0 then
    raise exception 'invalid_stock' using errcode = '22023';
  end if;

  select stock into v_old from public.flavors where id = p_flavor_id for update;
  if not found then
    raise exception 'flavor_not_found' using errcode = 'P0002';
  end if;

  update public.flavors set stock = p_stock where id = p_flavor_id;

  insert into public.stock_logs (flavor_id, delta, reason, note, actor_id)
  values (p_flavor_id, p_stock - v_old, 'manual', coalesce(p_note, ''), auth.uid());

  return jsonb_build_object('id', p_flavor_id, 'stock', p_stock);
end;
$$;

-- Simpan pengaturan ---------------------------------------------------------
create or replace function public.admin_save_settings(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  insert into public.store_settings (
    id, store_name, tagline_id, tagline_en, description_id, description_en,
    whatsapp, address, maps_url, instagram, tiktok, hours_id, hours_en,
    deadline_id, deadline_en, min_order, max_per_order, delivery_fee,
    free_shipping_min, bank_accounts, qris_enabled, qris_image_url,
    announcement_id, announcement_en, is_preorder_open
  ) values (
    1,
    coalesce(nullif(btrim(p_payload ->> 'store_name'), ''), 'Japanese Sando'),
    coalesce(p_payload ->> 'tagline_id', ''),
    coalesce(p_payload ->> 'tagline_en', ''),
    coalesce(p_payload ->> 'description_id', ''),
    coalesce(p_payload ->> 'description_en', ''),
    regexp_replace(coalesce(p_payload ->> 'whatsapp', ''), '\D', '', 'g'),
    coalesce(p_payload ->> 'address', ''),
    coalesce(p_payload ->> 'maps_url', ''),
    coalesce(p_payload ->> 'instagram', ''),
    coalesce(p_payload ->> 'tiktok', ''),
    coalesce(p_payload ->> 'hours_id', ''),
    coalesce(p_payload ->> 'hours_en', ''),
    coalesce(p_payload ->> 'deadline_id', ''),
    coalesce(p_payload ->> 'deadline_en', ''),
    greatest(1, coalesce((p_payload ->> 'min_order')::integer, 1)),
    greatest(1, coalesce((p_payload ->> 'max_per_order')::integer, 20)),
    greatest(0, coalesce((p_payload ->> 'delivery_fee')::integer, 0)),
    greatest(0, coalesce((p_payload ->> 'free_shipping_min')::integer, 0)),
    case when jsonb_typeof(p_payload -> 'bank_accounts') = 'array'
         then p_payload -> 'bank_accounts' else '[]'::jsonb end,
    coalesce((p_payload ->> 'qris_enabled')::boolean, false),
    nullif(trim(coalesce(p_payload ->> 'qris_image_url', '')), ''),
    coalesce(p_payload ->> 'announcement_id', ''),
    coalesce(p_payload ->> 'announcement_en', ''),
    coalesce((p_payload ->> 'is_preorder_open')::boolean, true)
  )
  on conflict (id) do update set
    store_name        = excluded.store_name,
    tagline_id        = excluded.tagline_id,
    tagline_en        = excluded.tagline_en,
    description_id    = excluded.description_id,
    description_en    = excluded.description_en,
    whatsapp          = excluded.whatsapp,
    address           = excluded.address,
    maps_url          = excluded.maps_url,
    instagram         = excluded.instagram,
    tiktok            = excluded.tiktok,
    hours_id          = excluded.hours_id,
    hours_en          = excluded.hours_en,
    deadline_id       = excluded.deadline_id,
    deadline_en       = excluded.deadline_en,
    min_order         = excluded.min_order,
    max_per_order     = excluded.max_per_order,
    delivery_fee      = excluded.delivery_fee,
    free_shipping_min = excluded.free_shipping_min,
    bank_accounts     = excluded.bank_accounts,
    qris_enabled      = excluded.qris_enabled,
    qris_image_url    = excluded.qris_image_url,
    announcement_id   = excluded.announcement_id,
    announcement_en   = excluded.announcement_en,
    is_preorder_open  = excluded.is_preorder_open;

  return jsonb_build_object('ok', true);
end;
$$;

-- Ringkasan dashboard -------------------------------------------------------
create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'pending_orders',   (select count(*) from public.orders where status = 'pending'),
    'accepted_orders',  (select count(*) from public.orders where status = 'accepted'),
    'ready_orders',     (select count(*) from public.orders where status = 'ready'),
    'total_orders',     (select count(*) from public.orders),
    'revenue_today', coalesce((
      select sum(total_price) from public.orders
      where created_at::date = current_date
        and status in ('accepted','ready','delivered')
    ), 0),
    'orders_today',   (select count(*) from public.orders where created_at::date = current_date),
    'revenue_month', coalesce((
      select sum(total_price) from public.orders
      where created_at >= date_trunc('month', now())
        and status in ('accepted','ready','delivered')
    ), 0),
    'flavor_count',   (select count(*) from public.flavors where is_active),
    'low_stock', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', f.id, 'name_id', f.name_id, 'name_en', f.name_en, 'stock', f.stock
      ) order by f.stock asc)
      from public.flavors f
      where f.is_active and f.stock_enabled and f.stock <= 5
    ), '[]'::jsonb),
    'sales_by_flavor', coalesce((
      select jsonb_agg(
        jsonb_build_object('flavor_name', t.flavor_name, 'qty', t.qty)
        order by t.qty desc
      )
      from (
        select oi.flavor_name, sum(oi.quantity)::int as qty
        from public.order_items oi
        join public.orders o on o.id = oi.order_id
        where o.created_at >= date_trunc('month', now())
          and o.status in ('accepted','ready','delivered')
        group by oi.flavor_name
      ) t
    ), '[]'::jsonb)
  );
end;
$$;

-- Cek apakah sudah ada admin (untuk halaman /admin/setup) -------------------
create or replace function public.public_admin_count()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer from public.admins;
$$;

-- =============================================================================
-- 6. ROW LEVEL SECURITY
-- =============================================================================

alter table public.flavors        enable row level security;
alter table public.orders         enable row level security;
alter table public.order_items    enable row level security;
alter table public.admins         enable row level security;
alter table public.store_settings enable row level security;
alter table public.stock_logs     enable row level security;

-- ì •ì±… reading publik (hanya kolom yang dipakai etalase; tidak ada data sensitif
-- di flavors, jadi aman dibuka ke anon)
drop policy if exists flavors_public_read on public.flavors;
create policy flavors_public_read on public.flavors
for select using (true);

drop policy if exists flavors_admin_write on public.flavors;
create policy flavors_admin_write on public.flavors
for all using (public.is_admin()) with check (public.is_admin());
-- Pembeli tidak boleh menulis langsung ke tabel pesanan — harus lewat RPC
-- create_order() yang sudah melakukan validasi & penguncian stok.
drop policy if exists orders_admin_all on public.orders;
create policy orders_admin_all on public.orders
for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists order_items_admin_all on public.order_items;
create policy order_items_admin_all on public.order_items
for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists settings_public_read on public.store_settings;
create policy settings_public_read on public.store_settings
for select using (true);

drop policy if exists settings_admin_write on public.store_settings;
create policy settings_admin_write on public.store_settings
for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists admins_self_read on public.admins;
create policy admins_self_read on public.admins
for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists admins_admin_write on public.admins;
create policy admins_admin_write on public.admins
for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists stock_logs_admin_all on public.stock_logs;
create policy stock_logs_admin_all on public.stock_logs
for all using (public.is_admin()) with check (public.is_admin());
-- =============================================================================
-- 7. STORAGE
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'flavor-images', 'flavor-images', true, 5242880,
  array['image/jpeg','image/png','image/webp','image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-proofs', 'payment-proofs', false, 5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Foto produk: publik baca, admin tulis
drop policy if exists flavor_images_public_read on storage.objects;
create policy flavor_images_public_read on storage.objects
for select using (bucket_id = 'flavor-images');

drop policy if exists flavor_images_admin_write on storage.objects;
create policy flavor_images_admin_write on storage.objects
for all using (bucket_id = 'flavor-images' and public.is_admin())
with check (bucket_id = 'flavor-images' and public.is_admin());

-- Bukti bayar: TIDAK publik. Pembeli boleh unggah ke folder proofs/ saja,
-- hanya admin yang boleh membaca.
drop policy if exists payment_proofs_admin_read on storage.objects;
create policy payment_proofs_admin_read on storage.objects
for select using (bucket_id = 'payment-proofs' and public.is_admin());

drop policy if exists payment_proofs_anon_insert on storage.objects;
create policy payment_proofs_anon_insert on storage.objects
for insert to anon, authenticated
with check (
  bucket_id = 'payment-proofs'
  and (storage.foldername(name))[1] = 'proofs'
);

drop policy if exists payment_proofs_admin_delete on storage.objects;
create policy payment_proofs_admin_delete on storage.objects
for delete using (bucket_id = 'payment-proofs' and public.is_admin());

-- =============================================================================
-- 8. SEED AWAL
-- =============================================================================

insert into public.store_settings (id) values (1) on conflict (id) do nothing;

insert into public.flavors
  (slug, name_id, name_en, desc_id, desc_en, price, is_active, is_featured, stock_enabled, stock, sort_order)
values
  ('cookies-cream', 'Cookies & Cream', 'Cookies & Cream',
   'Roti panggang isi krim Oreo asli dengan taburan choco chip.',
   'Toasted bread filled with original Oreo cream, finished with choco chips.',
   18000, true, true, true, 20, 1),
  ('caramel-cheese', 'Caramel Cheese', 'Caramel Cheese',
   'Krim keju lembut dengan saus karamel manis yang legit.',
   'Soft cheese cream drizzled with rich, buttery caramel sauce.',
   18000, true, true, true, 20, 2),
  ('choco-matcha', 'Choco Matcha', 'Choco Matcha',
   'Es matcha premium bertabur coklat dan coklat hitam leleh.',
   'Premium matcha ice cream drizzled with melted dark chocolate.',
   18000, true, true, true, 20, 3),
  ('creme-brulee', 'Creme Brulee', 'Creme Brulee',
   'Krim telur dengan lapisan karamel crunchy yang karamelisasi.',
   'Egg custard cream topped with a crunchy caramelized layer.',
   18000, true, true, true, 20, 4),
  ('strawberry-cheese', 'Strawberry Cheese', 'Strawberry Cheese',
   'Krim keju dengan stroberi segar dan strawberry crush.',
   'Creamy cheese filling with fresh strawberries and strawberry crush.',
   18000, true, true, true, 20, 5)
on conflict (slug) do nothing;

-- =============================================================================
-- 9. PERBAIKAN: RLS pada schema auth
-- -----------------------------------------------------------------------------
-- Tabel di schema `auth` memakai Row Level Security. GoTrue (login & daftar
-- user) membaca/menulis tabel tersebut sebagai role `supabase_auth_admin`.
-- Normally role itu punya BYPASSRLS; kalau hilang, SEMUA login gagal dengan
-- error "Database error querying schema" (HTTP 500).
--
-- `alter role` tidak diizinkan di sini (role reserved, butuh superuser), jadi
-- kita beri policy permisif untuk role tersebut. Efeknya sama dengan
-- BYPASSRLS khusus untuk tabel auth.
-- =============================================================================
do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'instances',
    'users', 'identities', 'sessions', 'refresh_tokens', 'flow_state',
    'mfa_amr_claims', 'mfa_challenges', 'mfa_factors',
    'mfa_recovery_code_sets', 'mfa_recovery_codes',
    'one_time_tokens', 'audit_log_entries', 'sso_domains', 'sso_providers',
    'saml_providers', 'saml_relay_states', 'oauth_authorizations',
    'oauth_client_states', 'oauth_clients', 'oauth_consents',
    'webauthn_challenges', 'webauthn_credentials', 'custom_oauth_providers'
  ] loop
    -- Some auth tables are owned by another role; skip them quietly so this
    -- script still succeeds on projects where we don't own every table.
    begin
      execute format('drop policy if exists gotrue_full_access on auth.%I', v_table);
      execute format(
        'create policy gotrue_full_access on auth.%I
           for all to supabase_auth_admin using (true) with check (true)',
        v_table
      );
    exception when insufficient_privilege then
      raise notice 'Tabel auth.% owned by role lain, dilewati.', v_table;
    end;
  end loop;
end
$$;

-- =============================================================================
-- 10. Segarkan cache skema PostgREST
--     Tanpa ini, PostgREST masih memakai definisi fungsi LAMA dan
--     pemanggilan RPC baru akan gagal dengan PGRST202.
-- =============================================================================
notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');
